# Settings
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
PADDLE_PACE = 30
PADDLE_STRETCH = 5
BALL_PACE = 5
COLLISION_BUFFER = 22
# right player -> arrow controls
R_PLAYER_COORDINATES = (SCREEN_WIDTH/2 - 50, 0)
# left player -> w/s controls
L_PLAYER_COORDINATES = (-SCREEN_WIDTH/2 + 50, 0)